# Generated by Django 5.1.2 on 2024-11-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productcode', models.CharField(db_column='productCode', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('version', models.DecimalField(decimal_places=5, max_digits=10)),
                ('releasedate', models.DateTimeField(db_column='releaseDate')),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
