# Generated by Django 5.1.2 on 2024-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technicians',
            fields=[
                ('techid', models.AutoField(db_column='techID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'technicians',
                'managed': False,
            },
        ),
    ]
